//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOmarKamal.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class omarKamalEntities : DbContext
    {
        public omarKamalEntities()
            : base("name=omarKamalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<العملاء> العملاء { get; set; }
        public virtual DbSet<المبيعات> المبيعات { get; set; }
        public virtual DbSet<المخزن> المخزن { get; set; }
        public virtual DbSet<المشتريات> المشتريات { get; set; }
        public virtual DbSet<الموردين> الموردين { get; set; }
        public virtual DbSet<login> logins { get; set; }
    }
}
