//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOmarKamal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class الموردين
    {
        public int الكود { get; set; }
        public string اسم_المورد { get; set; }
        public Nullable<System.DateTime> التاريخ { get; set; }
        public Nullable<int> الصنف { get; set; }
        public string الموديل { get; set; }
        public Nullable<int> العدد { get; set; }
        public Nullable<double> السعر { get; set; }
        public Nullable<double> الاجمالى { get; set; }
        public Nullable<double> تورديد { get; set; }
        public Nullable<double> الرصيد { get; set; }
    
        public virtual المخزن المخزن { get; set; }
    }
}
