//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOmarKamal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class العملاء
    {
        public int id { get; set; }
        public string اسم_العميل { get; set; }
        public Nullable<double> المدفوع { get; set; }
        public Nullable<double> المتبقي { get; set; }
        public Nullable<int> رقم_كود_الصنف { get; set; }
        public Nullable<System.DateTime> التاريخ { get; set; }
        public Nullable<double> اجمالى_المبلغ { get; set; }
    
        public virtual المخزن المخزن { get; set; }
    }
}
