//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOmarKamal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class المخزن
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public المخزن()
        {
            this.المبيعات = new HashSet<المبيعات>();
            this.المشتريات = new HashSet<المشتريات>();
            this.الموردين = new HashSet<الموردين>();
            this.العملاء = new HashSet<العملاء>();
        }
    
        public int الكود { get; set; }
        public Nullable<System.DateTime> التاريخ { get; set; }
        public string اسم_الصنف { get; set; }
        public string الموديل { get; set; }
        public Nullable<int> رصيد_أول_المده { get; set; }
        public Nullable<int> رصيد_اخر_المده { get; set; }
        public string اسم_معدل_الجدول { get; set; }
        public Nullable<System.DateTime> تاريخ_التعديل { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<المبيعات> المبيعات { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<المشتريات> المشتريات { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<الموردين> الموردين { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<العملاء> العملاء { get; set; }
    }
}
